### ISSUE TITLE
Error!!!!

### ISSUE THREAD

**Issue by shinexMC** [OpenFarLands/TheStoneProxy#8]
```
2024/02/23 11:24:59 Starting listening on 0.0.0.0:19132, proxying to 15.235.212.9:19132.
panic: runtime error: index out of range [10] with length 9

goroutine 7 [running]:
github.com/OpenFarLands/TheStoneProxy/src/server.(*Server).StartHandle.func1()
        D:/a/TheStoneProxy/TheStoneProxy/src/server/server.go:175 +0x430
created by github.com/OpenFarLands/TheStoneProxy/src/server.(*Server).StartHandle in goroutine 20
        D:/a/TheStoneProxy/TheStoneProxy/src/server/server.go:161 +0x1fb
```
how to fix this error

**Comment by mikhaillav** [comment]
that's a bug, because of invalid pong packet format (should be like this https://wiki.bedrock.dev/servers/raknet-and-mcpe.html#unconnected-pongs)

im gonna fix it

**Comment by mikhaillav** [comment]
Thank you for your contribution!
The bug has been fixed in latest [release](https://github.com/OpenFarLands/TheStoneProxy/releases/tag/v2.0.2).
